#------------------------------------------------------
# Configuration file for the Proxy Server
# This file defines multiple sources, pipelines, and destinations for the proxy server.
# Each source listens on a specific protocol (TCP, UDP, AWS S3, GCP, Azure Blob, Splunk HEC),
# applies a pipeline of transformations, and forwards the processed data to one or more destinations.
#------------------------------------------------------

sources:
  #-----------------Source 1: Syslog (UDP)--------------
  - name: _s_syslog_udp
    enabled: false       # Enable or disable this source
    protocol: udp       # Protocol: udp
    listen_ip: 0.0.0.0  # IP address to listen on
    listen_port: 514    # Standard Syslog UDP port
    pipeline:           # Pipeline transformations to apply
      - type: regex_replace
        field: raw_data
        pattern: "\\bERROR\\b"  # Regex pattern to match
        replacement: "[ALERT]"  # Replacement string
    destinations:       # List of destinations to forward data to
      - ip: 192.168.1.100
        port: 1601
        protocol: syslog_udp
      - ip: 192.168.1.100
        port: 1601
        protocol: syslog_tcp
  # End of Source 1 Configuration
#------------------------------------------------------
#---------------Source 2: Syslog (TCP)-----------------
  - name: _s_syslog_tcp
    enabled: false      # Enable or disable this source
    protocol: tcp       # Protocol: tcp
    listen_ip: 0.0.0.0  # IP address to listen on
    listen_port: 601    # Standard Syslog TCP port
    pipeline:           # Pipeline transformations to apply
      - type: regex_replace
        field: raw_data
        pattern: "\\bWARNING\\b"  # Regex pattern to match
        replacement: "[NOTICE]"    # Replacement string
    destinations:       # List of destinations to forward data to
      - ip: 192.168.1.102
        port: 514
        protocol: syslog_udp
      - ip: 192.168.1.103
        port: 601
        protocol: syslog_tcp
# End of Source 2 Configuration
#------------------------------------------------------

#---------------Source 3: RAW (UDP))-----------------
  - name: _s_raw_udp
    enabled: false      # Enable or disable this source
    protocol: udp       # Protocol: tcp
    listen_ip: 0.0.0.0  # IP address to listen on
    listen_port: 1514    # Standard Syslog TCP port
    pipeline:           # Pipeline transformations to apply
      - type: regex_replace
        field: syslog_message
        pattern: "\\bCRITICAL\\b"  # Regex pattern to match
        replacement: "[SEVERE]"    # Replacement string
    destinations:       # List of destinations to forward data to
      - ip: 192.168.1.100
        port: 9202      # Primary destination
# End of Source 3 Configuration
#------------------------------------------------------
#---------------Source 4: RAW (TCP)-----------------
  - name: _s_raw_tcp
    enabled: true       # Enable or disable this source
    protocol: tcp       # Protocol: tcp
    listen_ip: 0.0.0.0  # IP address to listen on
    listen_port: 1514    # Standard Syslog TCP port
    pipeline:           # Pipeline transformations to apply
      - type: regex_replace
        field: syslog_message
        pattern: "\\bCRITICAL\\b"  # Regex pattern to match
        replacement: "[SEVERE]"    # Replacement string
    destinations:       # List of destinations to forward data to
      - ip: 192.168.1.100
        id: __Output_d_raw_tcp
        port: 9202      # Primary destination
        protocol: udp
      - ip: 192.168.1.103
        name: 192.168.1.100_d_raw_tcp
        port: 601
        protocol: udp
# End of Source 4 Configuration
#------------------------------------------------------




#               ***** Collectors *****
  #-----------------Source 1C: AWS S3 collector------------
  - name: _s_s3_collector
    enabled: false       # Enable or disable this source
    protocol: s3        # Protocol: s3
    bucket_name: my-source-bucket  # Name of the S3 bucket to fetch data from
    region: us-east-1   # AWS region of the bucket
    polling_interval: 60  # Time interval (in seconds) to poll the bucket for new files
    pipeline:           # Pipeline transformations to apply
      - type: regex_replace
        field: file_content
        pattern: "\\bconfidential\\b"  # Regex pattern to match
        replacement: "[REDACTED]"      # Replacement string
    destinations:       # List of destinations to forward data to
      - bucket_name: my-destination-bucket     # S3 destination bucket
        region: us-east-1
# End of Source 1c Configuration
#------------------------------------------------------
#----------------Source 2C: GCP collector----------------------
  - name: _s_gcp_collector
    enabled: false      # Enable or disable this source
    protocol: gcp       # Protocol: gcp
    bucket_name: my-gcp-source-bucket  # Name of the GCP bucket to fetch data from
    polling_interval: 60  # Time interval (in seconds) to poll the bucket for new files
    pipeline:           # Pipeline transformations to apply
      - type: regex_replace
        field: file_content
        pattern: "\\bconfidential\\b"  # Regex pattern to match
        replacement: "[REDACTED]"      # Replacement string
    destinations:       # List of destinations to forward data to
      - bucket_name: my-gcp-destination-bucket  # GCP destination bucket
  # End of Source 2C Configuration
  #------------------------------------------------------
  #-----------------Source 3C: Azure Blob Storage collector---------------
  - name: _s_azure_blob_collector
    enabled: false       # Enable or disable this source
    protocol: azure_blob  # Protocol: azure_blob
    container_name: my-container  # Name of the Azure Blob container
    polling_interval: 60  # Time interval (in seconds) to poll the container for new files
    pipeline:           # Pipeline transformations to apply
      - type: regex_replace
        field: blob_content
        pattern: "\\bconfidential\\b"  # Regex pattern to match
        replacement: "[REDACTED]"      # Replacement string
    destinations:       # List of destinations to forward data to
      - container_name: my-destination-container  # Azure Blob destination container
  # End of Source 3C Configuration
  #----------------------------------------------------------------------
  #-----------------Source 4C: Splunk HEC collector-----------------------
  - name: _s_splunk_hec_collector
    enabled: false       # Enable or disable this source
    protocol: tcp       # Protocol: tcp
    listen_ip: 0.0.0.0  # IP address to listen on
    listen_port: 8088    # Standard Syslog TCP port
    #protocol: splunk_hec  # Protocol: splunk_hec
    endpoint: /services/collector  # Splunk HEC endpoint
    token: CF179AE4-3C99-45F5-A7CC-3284AA91CF67  # Splunk HEC authentication token
    pipeline:           # Pipeline transformations to apply
      - type: regex_replace
        field: event
        pattern: "\\bERROR\\b"  # Regex pattern to match
        replacement: "[ALERT]"  # Replacement string
    destinations:       # List of destinations to forward data to
      - url: http://splunk-server:8088/services/collector  # Splunk HEC destination
        token: YOUR_SPLUNK_HEC_DEST_TOKEN
  # End of Source 4C Configuration
  #-----------------------------------------------------------------------
